version: '3.9'

services:
  server:
    build: .
    image: "homework_01"
    ports:
      - "10000:10000"
    environment:
      PORT: 10000
    networks:
      - cloud_network

networks:
  cloud_network:
    external: false